name: sd_yq
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - ncurses=6.3
  - openssl=1.1.1w
  - pip=23.3.1
  - python=3.10.4
  - readline=8.1.2
  - setuptools=68.2.2
  - sqlite=3.38.5
  - tk=8.6.12
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - absl-py==2.1.0
    - accelerate==0.28.0
    - addict==2.4.0
    - aiofiles==23.2.1
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - altair==5.3.0
    - annotated-types==0.6.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.3.0
    - async-timeout==4.0.3
    - attrs==23.2.0
    - basicsr==1.4.2
    - bcrypt==4.1.2
    - beautifulsoup4==4.12.3
    - certifi==2024.2.2
    - cffi==1.16.0
    - cfgv==3.4.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - colossalai==0.3.6
    - contexttimer==0.3.3
    - contourpy==1.2.1
    - cryptography==42.0.5
    - cycler==0.12.1
    - datasets==2.19.1
    - decorator==4.4.2
    - decord==0.6.0
    - deepspeed==0.14.0
    - defusedxml==0.7.1
    - deprecated==1.2.14
    - diffusers==0.27.2
    - dill==0.3.8
    - distlib==0.3.8
    - einops==0.7.0
    - exceptiongroup==1.2.1
    - fabric==3.2.2
    - fairscale==0.4.13
    - fastapi==0.98.0
    - ffmpy==0.3.2
    - filelock==3.13.1
    - fonttools==4.51.0
    - frozenlist==1.4.1
    - fsspec==2024.3.1
    - future==1.0.0
    - google==3.0.0
    - gradio==4.27.0
    - gradio_client==0.15.1
    - groundingdino==0.1.0
    - grpcio==1.62.1
    - h11==0.14.0
    - hjson==3.1.0
    - httpcore==1.0.5
    - httptools==0.6.1
    - httpx==0.27.0
    - huggingface-hub==0.21.4
    - hydra-core==1.3.2
    - identify==2.5.35
    - idna==3.6
    - imageio==2.34.0
    - imageio-ffmpeg==0.4.9
    - importlib_metadata==7.0.2
    - importlib_resources==6.4.0
    - invoke==2.2.0
    - jinja2==3.1.3
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - kiwisolver==1.4.5
    - lazy_loader==0.4
    - lightning-utilities==0.11.2
    - lmdb==1.4.1
    - markdown==3.6
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.8.4
    - mdurl==0.1.2
    - moviepy==1.0.3
    - mpmath==1.3.0
    - msgpack==1.0.8
    - multidict==6.0.5
    - multiprocess==0.70.16
    - natsort==8.4.0
    - networkx==3.2.1
    - ninja==1.11.1.1
    - nodeenv==1.8.0
    - numpy==1.26.4
    - omegaconf==2.3.0
    - opencv-python==4.9.0.80
    - opencv-python-headless==4.10.0.84
    - orjson==3.10.1
    - packaging==24.0
    - pandas==2.2.1
    - paramiko==3.4.0
    - peft==0.10.0
    - pillow==9.2.0
    - platformdirs==4.2.0
    - pre-commit==3.6.2
    - proglog==0.1.10
    - protobuf==4.25.3
    - psutil==5.9.8
    - py-cpuinfo==9.0.0
    - pyarrow==16.0.0
    - pyarrow-hotfix==0.6
    - pyav==12.0.5
    - pycocotools==2.0.8
    - pycparser==2.21
    - pydantic==2.0
    - pydantic_core==2.0.1
    - pydub==0.25.1
    - pygments==2.17.2
    - pynacl==1.5.0
    - pynvml==11.5.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - python-multipart==0.0.9
    - pytorch-lightning==2.2.0
    - pytz==2024.1
    - pyyaml==6.0.1
    - ray==2.9.3
    - referencing==0.34.0
    - regex==2023.12.25
    - requests==2.31.0
    - rich==13.7.1
    - rotary-embedding-torch==0.3.5
    - rpds-py==0.18.0
    - ruff==0.4.0
    - safetensors==0.4.2
    - scikit-image==0.23.2
    - scipy==1.13.0
    - segment-anything==1.0
    - semantic-version==2.10.0
    - sentencepiece==0.2.0
    - shellingham==1.5.4
    - six==1.16.0
    - sniffio==1.3.1
    - soupsieve==2.5
    - starlette==0.27.0
    - structlog==24.1.0
    - supervision==0.21.0
    - sympy==1.12
    - tb-nightly==2.17.0a20240428
    - tensorboard==2.16.2
    - tensorboard-data-server==0.7.2
    - thop==0.1.1.post2209072238
    - tifffile==2024.4.24
    - timm==0.9.16
    - tokenizers==0.15.2
    - tomli==2.0.1
    - tomlkit==0.12.0
    - toolz==0.12.1
    - torch==2.1.1+cu121
    - torchaudio==2.1.1+cu121
    - torchmetrics==1.3.2
    - torchvision==0.16.1+cu121
    - tqdm==4.66.2
    - transformers==4.38.2
    - triton==2.1.0
    - typer==0.12.3
    - typing_extensions==4.10.0
    - urllib3==2.2.1
    - uvicorn==0.29.0
    - uvloop==0.19.0
    - virtualenv==20.25.1
    - watchfiles==0.21.0
    - websockets==11.0.3
    - werkzeug==3.0.2
    - wrapt==1.16.0
    - xformers==0.0.23
    - xxhash==3.4.1
    - yapf==0.40.2
    - yarl==1.9.4
    - zipp==3.18.1

