# "ReplaceMe" will be overwritten by the values in group_config.json

# General
seed: 6
device: "cuda:0" # <-- change this to the GPU you want to use
debug: False # For logging DEBUG level messages otherwise INFO

# Dir
data_dir: ".."  # <-- change this to the path of the data directory, if you cloned the repo, leave it as "..", the inversion latents will be saved in AnyV2V/
model_name: "i2vgen-xl"
task_name: "Prompt-Based-Editing"
edited_video_name: "ReplaceMe"
output_dir: "${data_dir}/Results/${task_name}/${model_name}/${video_name}/${edited_video_name}/"

# Data
# image_size: [1280, 704]
image_size: [1024, 512]
video_dir: "${data_dir}/demo"
video_name: "ReplaceMe"
video_path: "ReplaceMe"
video_frames_path: "${video_dir}/${video_name}"
edited_first_frame_path: "ReplaceMe"
ddim_latents_path: "${data_dir}/inversions/${model_name}/${video_name}/ddim_latents" # Same as inverse_config.output_dir

#background_video_generate
generated_bacground: False
generated_bacground_prompt: "ReplaceMe"
generated_bacground_negative_prompt: "Chaotic, chaotic colors,Distorted, discontinuous, Ugly, blurry, low resolution, motionless, static, disfigured, disconnected limbs, Ugly faces, incomplete arms"
generated_bacground_path: "${data_dir}/generated_bacground/"


# noise fusion or feature fusion config
random_noise_ratio: 0.8
fusion_step: [0, 3]

# Pnp Editing
n_frames: 16
cfg: 9.0  #9.0
target_fps: 8
editing_prompt: "ReplaceMe"
editing_negative_prompt: "Chaotic, chaotic colors,Distorted, discontinuous, Ugly, blurry, low resolution, motionless, static, disfigured, disconnected limbs, Ugly faces, incomplete arms"
n_steps: 50
ddim_init_latents_t_idx: 3  # 0 for 981, 3 for 921, 9 for 801, 20 for 581 if n_steps=50
ddim_inv_prompt: ""
random_ratio: 1.0  #0.0
# Pnp config
pnp_f_t: 0.2
pnp_spatial_attn_t: 0.2
pnp_temp_attn_t: 0.5
pnp_cross_attn_t: 0.0
inject_background: False

# object
obj_ddim_latents_path: ""
obj_ddim_latents_idx_offset: [0, 0]
obj_mask_path: "" # TODO: add multi-objects support
obj_width_height: []
obj_random_noise_fusion: False

# background
bg_ddim_latents_path: "${data_dir}/inversions/${model_name}/${video_name}/ddim_latents"

frameinit_kwargs:
  enable: true
  camera_motion: null
  noise_level: 850
  filter_params:
    method: 'gaussian'
    d_s: 0.25
    d_t: 0.25

# eidt prompt extraction
edited_contorl_frame_path: "" # object condition
edited_contorl_frame_path_main: ""
edited_contorl_frame_path_background: ""